POST http://localhost:3000/api/auth/register-usuario
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Pérez",
  "nombre_usuario": "juan123",
  "cedula": "123456789",
  "correo": "juan@email.com",
  "contraseña": "password123",
  "rol": "usuario"
}

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "nombre_usuario": "juan123",
  "contraseña": "password123"
}

POST http://localhost:3000/api/paquetes
Authorization: Bearer <tu_token>
Content-Type: application/json

{
  "titulo": "Paquete Playa",
  "descripcion": "Disfruta de un día en la playa",
  "precio": 100,
  "destino": "Buenaventura",
  "incluye_transporte": true,
  "hotel_frente_mar": false,
  "comidas_incluidas": true
}